import { db } from "../firebase";
import { doc, setDoc } from "firebase/firestore";

const PARTIDOS = [
  {
    id: 1,
    fecha: "2026-06-11T19:00:00Z",
    grupo: "Grupo A",
    jornada: "Fase de Grupos",
    local: "México",
    visitante: "Sudáfrica",
    estadio: "Estadio Azteca",
    ciudad: "Ciudad de México",
  },
  {
    id: 2,
    fecha: "2026-06-12T02:00:00Z",
    grupo: "Grupo A",
    jornada: "Fase de Grupos",
    local: "Corea del Sur",
    visitante: "Chequia",
    estadio: "Estadio Akron",
    ciudad: "Guadalajara",
  },
  {
    id: 3,
    fecha: "2026-06-12T19:00:00Z",
    grupo: "Grupo B",
    jornada: "Fase de Grupos",
    local: "Canadá",
    visitante: "Bosnia Herzegovina",
    estadio: "BMO Field",
    ciudad: "Toronto",
  },
  {
    id: 4,
    fecha: "2026-06-13T01:00:00Z",
    grupo: "Grupo D",
    jornada: "Fase de Grupos",
    local: "Estados Unidos",
    visitante: "Paraguay",
    estadio: "SoFi Stadium",
    ciudad: "Inglewood",
  },
  {
    id: 5,
    fecha: "2026-06-13T19:00:00Z",
    grupo: "Grupo B",
    jornada: "Fase de Grupos",
    local: "Qatar",
    visitante: "Suiza",
    estadio: "Levi's Stadium",
    ciudad: "Santa Clara",
  },
  {
    id: 6,
    fecha: "2026-06-13T22:00:00Z",
    grupo: "Grupo C",
    jornada: "Fase de Grupos",
    local: "Brasil",
    visitante: "Marruecos",
    estadio: "MetLife Stadium",
    ciudad: "East Rutherford",
  },
  {
    id: 7,
    fecha: "2026-06-14T01:00:00Z",
    grupo: "Grupo C",
    jornada: "Fase de Grupos",
    local: "Haití",
    visitante: "Escocia",
    estadio: "Gillette Stadium",
    ciudad: "Foxborough",
  },
  {
    id: 8,
    fecha: "2026-06-14T16:00:00Z",
    grupo: "Grupo D",
    jornada: "Fase de Grupos",
    local: "Australia",
    visitante: "Türkiye",
    estadio: "BC Place",
    ciudad: "Vancouver",
  },
  {
    id: 9,
    fecha: "2026-06-14T17:00:00Z",
    grupo: "Grupo E",
    jornada: "Fase de Grupos",
    local: "Alemania",
    visitante: "Curaçao",
    estadio: "NRG Stadium",
    ciudad: "Houston",
  },
  {
    id: 10,
    fecha: "2026-06-14T20:00:00Z",
    grupo: "Grupo F",
    jornada: "Fase de Grupos",
    local: "Países Bajos",
    visitante: "Japón",
    estadio: "AT&T Stadium",
    ciudad: "Arlington",
  },
  {
    id: 11,
    fecha: "2026-06-14T23:00:00Z",
    grupo: "Grupo E",
    jornada: "Fase de Grupos",
    local: "Costa de Marfil",
    visitante: "Ecuador",
    estadio: "Lincoln Financial Field",
    ciudad: "Filadelfia",
  },
  {
    id: 12,
    fecha: "2026-06-15T02:00:00Z",
    grupo: "Grupo F",
    jornada: "Fase de Grupos",
    local: "Suecia",
    visitante: "Túnez",
    estadio: "Estadio BBVA",
    ciudad: "Monterrey",
  },
  {
    id: 13,
    fecha: "2026-06-15T16:00:00Z",
    grupo: "Grupo H",
    jornada: "Fase de Grupos",
    local: "España",
    visitante: "Cabo Verde",
    estadio: "Mercedes-Benz Stadium",
    ciudad: "Atlanta",
  },
  {
    id: 14,
    fecha: "2026-06-15T19:00:00Z",
    grupo: "Grupo G",
    jornada: "Fase de Grupos",
    local: "Bélgica",
    visitante: "Egipto",
    estadio: "Lumen Field",
    ciudad: "Seattle",
  },
  {
    id: 15,
    fecha: "2026-06-15T22:00:00Z",
    grupo: "Grupo H",
    jornada: "Fase de Grupos",
    local: "Arabia Saudita",
    visitante: "Uruguay",
    estadio: "Hard Rock Stadium",
    ciudad: "Miami Gardens",
  },
  {
    id: 16,
    fecha: "2026-06-16T01:00:00Z",
    grupo: "Grupo G",
    jornada: "Fase de Grupos",
    local: "Irán",
    visitante: "Nueva Zelanda",
    estadio: "SoFi Stadium",
    ciudad: "Inglewood",
  },
  {
    id: 17,
    fecha: "2026-06-16T19:00:00Z",
    grupo: "Grupo I",
    jornada: "Fase de Grupos",
    local: "Francia",
    visitante: "Senegal",
    estadio: "MetLife Stadium",
    ciudad: "East Rutherford",
  },
  {
    id: 18,
    fecha: "2026-06-16T22:00:00Z",
    grupo: "Grupo I",
    jornada: "Fase de Grupos",
    local: "Irak",
    visitante: "Noruega",
    estadio: "Gillette Stadium",
    ciudad: "Foxborough",
  },
  {
    id: 19,
    fecha: "2026-06-17T01:00:00Z",
    grupo: "Grupo J",
    jornada: "Fase de Grupos",
    local: "Argentina",
    visitante: "Argelia",
    estadio: "Arrowhead Stadium",
    ciudad: "Kansas City",
  },
  {
    id: 20,
    fecha: "2026-06-17T04:00:00Z",
    grupo: "Grupo J",
    jornada: "Fase de Grupos",
    local: "Austria",
    visitante: "Jordania",
    estadio: "Levi's Stadium",
    ciudad: "Santa Clara",
  },
  {
    id: 21,
    fecha: "2026-06-17T17:00:00Z",
    grupo: "Grupo K",
    jornada: "Fase de Grupos",
    local: "Portugal",
    visitante: "R. D. Congo",
    estadio: "NRG Stadium",
    ciudad: "Houston",
  },
  {
    id: 22,
    fecha: "2026-06-17T20:00:00Z",
    grupo: "Grupo L",
    jornada: "Fase de Grupos",
    local: "Inglaterra",
    visitante: "Croacia",
    estadio: "AT&T Stadium",
    ciudad: "Arlington",
  },
  {
    id: 23,
    fecha: "2026-06-17T23:00:00Z",
    grupo: "Grupo L",
    jornada: "Fase de Grupos",
    local: "Ghana",
    visitante: "Panamá",
    estadio: "BMO Field",
    ciudad: "Toronto",
  },
  {
    id: 24,
    fecha: "2026-06-18T02:00:00Z",
    grupo: "Grupo K",
    jornada: "Fase de Grupos",
    local: "Uzbekistán",
    visitante: "Colombia",
    estadio: "Estadio Azteca",
    ciudad: "Ciudad de México",
  },
  {
    id: 25,
    fecha: "2026-06-18T16:00:00Z",
    grupo: "Grupo A",
    jornada: "Fase de Grupos",
    local: "Chequia",
    visitante: "Sudáfrica",
    estadio: "Mercedes-Benz Stadium",
    ciudad: "Atlanta",
  },
  {
    id: 26,
    fecha: "2026-06-18T19:00:00Z",
    grupo: "Grupo B",
    jornada: "Fase de Grupos",
    local: "Suiza",
    visitante: "Bosnia Herzegovina",
    estadio: "SoFi Stadium",
    ciudad: "Inglewood",
  },
  {
    id: 27,
    fecha: "2026-06-18T22:00:00Z",
    grupo: "Grupo B",
    jornada: "Fase de Grupos",
    local: "Canadá",
    visitante: "Qatar",
    estadio: "BC Place",
    ciudad: "Vancouver",
  },
  {
    id: 28,
    fecha: "2026-06-19T01:00:00Z",
    grupo: "Grupo A",
    jornada: "Fase de Grupos",
    local: "México",
    visitante: "Corea del Sur",
    estadio: "Estadio Akron",
    ciudad: "Guadalajara",
  },
  {
    id: 29,
    fecha: "2026-06-19T19:00:00Z",
    grupo: "Grupo D",
    jornada: "Fase de Grupos",
    local: "Estados Unidos",
    visitante: "Australia",
    estadio: "Lumen Field",
    ciudad: "Seattle",
  },
  {
    id: 30,
    fecha: "2026-06-19T22:00:00Z",
    grupo: "Grupo C",
    jornada: "Fase de Grupos",
    local: "Escocia",
    visitante: "Marruecos",
    estadio: "Gillette Stadium",
    ciudad: "Foxborough",
  },
  {
    id: 31,
    fecha: "2026-06-20T00:30:00Z",
    grupo: "Grupo C",
    jornada: "Fase de Grupos",
    local: "Brasil",
    visitante: "Haití",
    estadio: "Lincoln Financial Field",
    ciudad: "Filadelfia",
  },
  {
    id: 32,
    fecha: "2026-06-20T03:00:00Z",
    grupo: "Grupo D",
    jornada: "Fase de Grupos",
    local: "Türkiye",
    visitante: "Paraguay",
    estadio: "Levi's Stadium",
    ciudad: "Santa Clara",
  },
  {
    id: 33,
    fecha: "2026-06-20T17:00:00Z",
    grupo: "Grupo F",
    jornada: "Fase de Grupos",
    local: "Países Bajos",
    visitante: "Suecia",
    estadio: "NRG Stadium",
    ciudad: "Houston",
  },
  {
    id: 34,
    fecha: "2026-06-20T20:00:00Z",
    grupo: "Grupo E",
    jornada: "Fase de Grupos",
    local: "Alemania",
    visitante: "Costa de Marfil",
    estadio: "BMO Field",
    ciudad: "Toronto",
  },
  {
    id: 35,
    fecha: "2026-06-21T00:00:00Z",
    grupo: "Grupo E",
    jornada: "Fase de Grupos",
    local: "Ecuador",
    visitante: "Curaçao",
    estadio: "Arrowhead Stadium",
    ciudad: "Kansas City",
  },
  {
    id: 36,
    fecha: "2026-06-21T04:00:00Z",
    grupo: "Grupo F",
    jornada: "Fase de Grupos",
    local: "Túnez",
    visitante: "Japón",
    estadio: "Estadio BBVA",
    ciudad: "Monterrey",
  },
  {
    id: 37,
    fecha: "2026-06-21T16:00:00Z",
    grupo: "Grupo H",
    jornada: "Fase de Grupos",
    local: "España",
    visitante: "Arabia Saudita",
    estadio: "Mercedes-Benz Stadium",
    ciudad: "Atlanta",
  },
  {
    id: 38,
    fecha: "2026-06-21T19:00:00Z",
    grupo: "Grupo G",
    jornada: "Fase de Grupos",
    local: "Bélgica",
    visitante: "Irán",
    estadio: "SoFi Stadium",
    ciudad: "Inglewood",
  },
  {
    id: 39,
    fecha: "2026-06-21T22:00:00Z",
    grupo: "Grupo H",
    jornada: "Fase de Grupos",
    local: "Uruguay",
    visitante: "Cabo Verde",
    estadio: "Hard Rock Stadium",
    ciudad: "Miami Gardens",
  },
  {
    id: 40,
    fecha: "2026-06-22T01:00:00Z",
    grupo: "Grupo G",
    jornada: "Fase de Grupos",
    local: "Nueva Zelanda",
    visitante: "Egipto",
    estadio: "BC Place",
    ciudad: "Vancouver",
  },
  {
    id: 41,
    fecha: "2026-06-22T17:00:00Z",
    grupo: "Grupo J",
    jornada: "Fase de Grupos",
    local: "Argentina",
    visitante: "Austria",
    estadio: "AT&T Stadium",
    ciudad: "Arlington",
  },
  {
    id: 42,
    fecha: "2026-06-22T21:00:00Z",
    grupo: "Grupo I",
    jornada: "Fase de Grupos",
    local: "Francia",
    visitante: "Irak",
    estadio: "Lincoln Financial Field",
    ciudad: "Filadelfia",
  },
  {
    id: 43,
    fecha: "2026-06-23T00:00:00Z",
    grupo: "Grupo I",
    jornada: "Fase de Grupos",
    local: "Noruega",
    visitante: "Senegal",
    estadio: "MetLife Stadium",
    ciudad: "East Rutherford",
  },
  {
    id: 44,
    fecha: "2026-06-23T03:00:00Z",
    grupo: "Grupo J",
    jornada: "Fase de Grupos",
    local: "Jordania",
    visitante: "Argelia",
    estadio: "Levi's Stadium",
    ciudad: "Santa Clara",
  },
  {
    id: 45,
    fecha: "2026-06-23T17:00:00Z",
    grupo: "Grupo K",
    jornada: "Fase de Grupos",
    local: "Portugal",
    visitante: "Uzbekistán",
    estadio: "NRG Stadium",
    ciudad: "Houston",
  },
  {
    id: 46,
    fecha: "2026-06-23T20:00:00Z",
    grupo: "Grupo L",
    jornada: "Fase de Grupos",
    local: "Inglaterra",
    visitante: "Panamá",
    estadio: "AT&T Stadium",
    ciudad: "Arlington",
  },
  {
    id: 47,
    fecha: "2026-06-23T23:00:00Z",
    grupo: "Grupo K",
    jornada: "Fase de Grupos",
    local: "Colombia",
    visitante: "R. D. Congo",
    estadio: "Estadio Azteca",
    ciudad: "Ciudad de México",
  },
  {
    id: 48,
    fecha: "2026-06-24T02:00:00Z",
    grupo: "Grupo L",
    jornada: "Fase de Grupos",
    local: "Croacia",
    visitante: "Ghana",
    estadio: "BMO Field",
    ciudad: "Toronto",
  },
  {
    id: 49,
    fecha: "2026-06-24T19:00:00Z",
    grupo: "Grupo A",
    jornada: "Fase de Grupos",
    local: "Sudáfrica",
    visitante: "México",
    estadio: "Lumen Field",
    ciudad: "Seattle",
  },
  {
    id: 50,
    fecha: "2026-06-24T19:00:00Z",
    grupo: "Grupo A",
    jornada: "Fase de Grupos",
    local: "Chequia",
    visitante: "Corea del Sur",
    estadio: "Gillette Stadium",
    ciudad: "Foxborough",
  },
  {
    id: 51,
    fecha: "2026-06-25T01:00:00Z",
    grupo: "Grupo B",
    jornada: "Fase de Grupos",
    local: "Qatar",
    visitante: "Bosnia Herzegovina",
    estadio: "Lincoln Financial Field",
    ciudad: "Filadelfia",
  },
  {
    id: 52,
    fecha: "2026-06-25T01:00:00Z",
    grupo: "Grupo B",
    jornada: "Fase de Grupos",
    local: "Suiza",
    visitante: "Canadá",
    estadio: "Arrowhead Stadium",
    ciudad: "Kansas City",
  },
  {
    id: 53,
    fecha: "2026-06-25T19:00:00Z",
    grupo: "Grupo C",
    jornada: "Fase de Grupos",
    local: "Marruecos",
    visitante: "Brasil",
    estadio: "Estadio BBVA",
    ciudad: "Monterrey",
  },
  {
    id: 54,
    fecha: "2026-06-25T19:00:00Z",
    grupo: "Grupo C",
    jornada: "Fase de Grupos",
    local: "Escocia",
    visitante: "Haití",
    estadio: "Estadio Akron",
    ciudad: "Guadalajara",
  },
  {
    id: 55,
    fecha: "2026-06-26T01:00:00Z",
    grupo: "Grupo D",
    jornada: "Fase de Grupos",
    local: "Paraguay",
    visitante: "Australia",
    estadio: "Mercedes-Benz Stadium",
    ciudad: "Atlanta",
  },
  {
    id: 56,
    fecha: "2026-06-26T01:00:00Z",
    grupo: "Grupo D",
    jornada: "Fase de Grupos",
    local: "Türkiye",
    visitante: "Estados Unidos",
    estadio: "SoFi Stadium",
    ciudad: "Inglewood",
  },
  {
    id: 57,
    fecha: "2026-06-26T19:00:00Z",
    grupo: "Grupo E",
    jornada: "Fase de Grupos",
    local: "Curaçao",
    visitante: "Alemania",
    estadio: "BC Place",
    ciudad: "Vancouver",
  },
  {
    id: 58,
    fecha: "2026-06-26T19:00:00Z",
    grupo: "Grupo E",
    jornada: "Fase de Grupos",
    local: "Ecuador",
    visitante: "Costa de Marfil",
    estadio: "NRG Stadium",
    ciudad: "Houston",
  },
  {
    id: 59,
    fecha: "2026-06-27T01:00:00Z",
    grupo: "Grupo F",
    jornada: "Fase de Grupos",
    local: "Japón",
    visitante: "Países Bajos",
    estadio: "AT&T Stadium",
    ciudad: "Arlington",
  },
  {
    id: 60,
    fecha: "2026-06-27T01:00:00Z",
    grupo: "Grupo F",
    jornada: "Fase de Grupos",
    local: "Túnez",
    visitante: "Suecia",
    estadio: "BMO Field",
    ciudad: "Toronto",
  },
  {
    id: 61,
    fecha: "2026-06-27T19:00:00Z",
    grupo: "Grupo G",
    jornada: "Fase de Grupos",
    local: "Egipto",
    visitante: "Bélgica",
    estadio: "Lumen Field",
    ciudad: "Seattle",
  },
  {
    id: 62,
    fecha: "2026-06-27T19:00:00Z",
    grupo: "Grupo G",
    jornada: "Fase de Grupos",
    local: "Nueva Zelanda",
    visitante: "Irán",
    estadio: "Estadio Azteca",
    ciudad: "Ciudad de México",
  },
  {
    id: 63,
    fecha: "2026-06-28T01:00:00Z",
    grupo: "Grupo H",
    jornada: "Fase de Grupos",
    local: "Cabo Verde",
    visitante: "España",
    estadio: "Gillette Stadium",
    ciudad: "Foxborough",
  },
  {
    id: 64,
    fecha: "2026-06-28T01:00:00Z",
    grupo: "Grupo H",
    jornada: "Fase de Grupos",
    local: "Uruguay",
    visitante: "Arabia Saudita",
    estadio: "Lincoln Financial Field",
    ciudad: "Filadelfia",
  },
  {
    id: 65,
    fecha: "2026-06-28T19:00:00Z",
    grupo: "Grupo I",
    jornada: "Fase de Grupos",
    local: "Senegal",
    visitante: "Francia",
    estadio: "Arrowhead Stadium",
    ciudad: "Kansas City",
  },
  {
    id: 66,
    fecha: "2026-06-28T19:00:00Z",
    grupo: "Grupo I",
    jornada: "Fase de Grupos",
    local: "Noruega",
    visitante: "Irak",
    estadio: "Estadio BBVA",
    ciudad: "Monterrey",
  },
  {
    id: 67,
    fecha: "2026-06-29T01:00:00Z",
    grupo: "Grupo J",
    jornada: "Fase de Grupos",
    local: "Argelia",
    visitante: "Argentina",
    estadio: "Estadio Akron",
    ciudad: "Guadalajara",
  },
  {
    id: 68,
    fecha: "2026-06-29T01:00:00Z",
    grupo: "Grupo J",
    jornada: "Fase de Grupos",
    local: "Jordania",
    visitante: "Austria",
    estadio: "Mercedes-Benz Stadium",
    ciudad: "Atlanta",
  },
  {
    id: 69,
    fecha: "2026-06-29T19:00:00Z",
    grupo: "Grupo K",
    jornada: "Fase de Grupos",
    local: "R. D. Congo",
    visitante: "Uzbekistán",
    estadio: "SoFi Stadium",
    ciudad: "Inglewood",
  },
  {
    id: 70,
    fecha: "2026-06-29T19:00:00Z",
    grupo: "Grupo K",
    jornada: "Fase de Grupos",
    local: "Colombia",
    visitante: "Portugal",
    estadio: "BC Place",
    ciudad: "Vancouver",
  },
  {
    id: 71,
    fecha: "2026-06-30T01:00:00Z",
    grupo: "Grupo L",
    jornada: "Fase de Grupos",
    local: "Panamá",
    visitante: "Croacia",
    estadio: "NRG Stadium",
    ciudad: "Houston",
  },
  {
    id: 72,
    fecha: "2026-06-30T01:00:00Z",
    grupo: "Grupo L",
    jornada: "Fase de Grupos",
    local: "Ghana",
    visitante: "Inglaterra",
    estadio: "AT&T Stadium",
    ciudad: "Arlington",
  },
  // Ronda de 32
  {
    id: 73,
    fecha: "2026-07-01T19:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo A",
    visitante: "3ro Grupo D/E/F",
    estadio: "BMO Field",
    ciudad: "Toronto",
  },
  {
    id: 74,
    fecha: "2026-07-01T22:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo C",
    visitante: "3ro Grupo A/B",
    estadio: "Lincoln Financial Field",
    ciudad: "Filadelfia",
  },
  {
    id: 75,
    fecha: "2026-07-02T01:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo B",
    visitante: "3ro Grupo G/H/I",
    estadio: "Lumen Field",
    ciudad: "Seattle",
  },
  {
    id: 76,
    fecha: "2026-07-02T19:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo D",
    visitante: "2do Grupo C",
    estadio: "Estadio Azteca",
    ciudad: "Ciudad de México",
  },
  {
    id: 77,
    fecha: "2026-07-02T22:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo F",
    visitante: "2do Grupo E",
    estadio: "Arrowhead Stadium",
    ciudad: "Kansas City",
  },
  {
    id: 78,
    fecha: "2026-07-03T01:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo E",
    visitante: "2do Grupo D",
    estadio: "Estadio Akron",
    ciudad: "Guadalajara",
  },
  {
    id: 79,
    fecha: "2026-07-03T19:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo G",
    visitante: "2do Grupo H",
    estadio: "Mercedes-Benz Stadium",
    ciudad: "Atlanta",
  },
  {
    id: 80,
    fecha: "2026-07-03T22:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo H",
    visitante: "2do Grupo G",
    estadio: "Hard Rock Stadium",
    ciudad: "Miami Gardens",
  },
  {
    id: 81,
    fecha: "2026-07-04T01:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo I",
    visitante: "2do Grupo J",
    estadio: "Levi's Stadium",
    ciudad: "Santa Clara",
  },
  {
    id: 82,
    fecha: "2026-07-04T19:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo J",
    visitante: "2do Grupo I",
    estadio: "NRG Stadium",
    ciudad: "Houston",
  },
  {
    id: 83,
    fecha: "2026-07-04T22:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo K",
    visitante: "2do Grupo L",
    estadio: "AT&T Stadium",
    ciudad: "Arlington",
  },
  {
    id: 84,
    fecha: "2026-07-05T01:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "1ro Grupo L",
    visitante: "2do Grupo K",
    estadio: "SoFi Stadium",
    ciudad: "Inglewood",
  },
  {
    id: 85,
    fecha: "2026-07-05T19:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "2do Grupo A",
    visitante: "2do Grupo B",
    estadio: "BC Place",
    ciudad: "Vancouver",
  },
  {
    id: 86,
    fecha: "2026-07-05T22:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "2do Grupo F",
    visitante: "3ro Grupo J/K/L",
    estadio: "Gillette Stadium",
    ciudad: "Foxborough",
  },
  {
    id: 87,
    fecha: "2026-07-06T01:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "3ro Grupo B/C",
    visitante: "3ro Grupo I/J/K",
    estadio: "MetLife Stadium",
    ciudad: "East Rutherford",
  },
  {
    id: 88,
    fecha: "2026-07-06T19:00:00Z",
    grupo: "-",
    jornada: "Ronda de 32",
    local: "3ro Grupo L/A/B",
    visitante: "3ro Grupo C/D",
    estadio: "Estadio BBVA",
    ciudad: "Monterrey",
  },
  // Octavos
  {
    id: 89,
    fecha: "2026-07-09T19:00:00Z",
    grupo: "-",
    jornada: "Octavos de Final",
    local: "Gan. P73",
    visitante: "Gan. P74",
    estadio: "MetLife Stadium",
    ciudad: "East Rutherford",
  },
  {
    id: 90,
    fecha: "2026-07-09T23:00:00Z",
    grupo: "-",
    jornada: "Octavos de Final",
    local: "Gan. P75",
    visitante: "Gan. P76",
    estadio: "SoFi Stadium",
    ciudad: "Inglewood",
  },
  {
    id: 91,
    fecha: "2026-07-10T19:00:00Z",
    grupo: "-",
    jornada: "Octavos de Final",
    local: "Gan. P77",
    visitante: "Gan. P78",
    estadio: "AT&T Stadium",
    ciudad: "Arlington",
  },
  {
    id: 92,
    fecha: "2026-07-10T23:00:00Z",
    grupo: "-",
    jornada: "Octavos de Final",
    local: "Gan. P79",
    visitante: "Gan. P80",
    estadio: "Levi's Stadium",
    ciudad: "Santa Clara",
  },
  {
    id: 93,
    fecha: "2026-07-11T19:00:00Z",
    grupo: "-",
    jornada: "Octavos de Final",
    local: "Gan. P81",
    visitante: "Gan. P82",
    estadio: "NRG Stadium",
    ciudad: "Houston",
  },
  {
    id: 94,
    fecha: "2026-07-11T23:00:00Z",
    grupo: "-",
    jornada: "Octavos de Final",
    local: "Gan. P83",
    visitante: "Gan. P84",
    estadio: "BC Place",
    ciudad: "Vancouver",
  },
  {
    id: 95,
    fecha: "2026-07-12T19:00:00Z",
    grupo: "-",
    jornada: "Octavos de Final",
    local: "Gan. P85",
    visitante: "Gan. P86",
    estadio: "Mercedes-Benz Stadium",
    ciudad: "Atlanta",
  },
  {
    id: 96,
    fecha: "2026-07-12T23:00:00Z",
    grupo: "-",
    jornada: "Octavos de Final",
    local: "Gan. P87",
    visitante: "Gan. P88",
    estadio: "Arrowhead Stadium",
    ciudad: "Kansas City",
  },
  // Cuartos
  {
    id: 97,
    fecha: "2026-07-14T23:00:00Z",
    grupo: "-",
    jornada: "Cuartos de Final",
    local: "Gan. P89",
    visitante: "Gan. P90",
    estadio: "MetLife Stadium",
    ciudad: "East Rutherford",
  },
  {
    id: 98,
    fecha: "2026-07-15T23:00:00Z",
    grupo: "-",
    jornada: "Cuartos de Final",
    local: "Gan. P91",
    visitante: "Gan. P92",
    estadio: "SoFi Stadium",
    ciudad: "Inglewood",
  },
  {
    id: 99,
    fecha: "2026-07-16T23:00:00Z",
    grupo: "-",
    jornada: "Cuartos de Final",
    local: "Gan. P93",
    visitante: "Gan. P94",
    estadio: "AT&T Stadium",
    ciudad: "Arlington",
  },
  {
    id: 100,
    fecha: "2026-07-17T23:00:00Z",
    grupo: "-",
    jornada: "Cuartos de Final",
    local: "Gan. P95",
    visitante: "Gan. P96",
    estadio: "Levi's Stadium",
    ciudad: "Santa Clara",
  },
  // Semifinales
  {
    id: 101,
    fecha: "2026-07-18T23:00:00Z",
    grupo: "-",
    jornada: "Semifinal",
    local: "Gan. P97",
    visitante: "Gan. P98",
    estadio: "MetLife Stadium",
    ciudad: "East Rutherford",
  },
  {
    id: 102,
    fecha: "2026-07-19T23:00:00Z",
    grupo: "-",
    jornada: "Semifinal",
    local: "Gan. P99",
    visitante: "Gan. P100",
    estadio: "AT&T Stadium",
    ciudad: "Arlington",
  },
  // Tercer puesto y Final
  {
    id: 103,
    fecha: "2026-07-18T20:00:00Z",
    grupo: "-",
    jornada: "Tercer Puesto",
    local: "Per. P101",
    visitante: "Per. P102",
    estadio: "Hard Rock Stadium",
    ciudad: "Miami Gardens",
  },
  {
    id: 104,
    fecha: "2026-07-19T20:00:00Z",
    grupo: "-",
    jornada: "Final",
    local: "Gan. P101",
    visitante: "Gan. P102",
    estadio: "MetLife Stadium",
    ciudad: "East Rutherford",
  },
];

export async function importarFixture() {
  console.log("🚀 Iniciando importación con datos locales...");

  try {
    for (const partido of PARTIDOS) {
      await setDoc(doc(db, "fixture", String(partido.id)), {
        fecha: partido.fecha,
        grupo: partido.grupo,
        jornada: partido.jornada,
        estado: "NS",
        local: { nombre: partido.local, goles: null },
        visitante: { nombre: partido.visitante, goles: null },
        estadio: partido.estadio,
        ciudad: partido.ciudad,
      });
    }

    alert(`✅ ${PARTIDOS.length} partidos importados correctamente`);
    console.log("✅ Hecho");
  } catch (e) {
    console.error("❌ Error:", e);
    alert("Error: " + e.message);
  }
}
